[build]
  publish = "dist"
  command = "npm run sync:content && npm run build"
[build.environment]
  VITE_APP_ENV = "production"
[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"